title = "Niklaas Baudet von Gersdorff"
base_url = "https://www.niklaas.eu"
compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags", feed = true, render = false},
]

[extra]
theme_title = "Niklaas's Notes"

