title: Niklaas's Notebook
description: I am writing about my experiences as a software engineer in the web development industry.
author:
  name: Niklaas Baudet von Gersdorff
  email: hello@niklaas.eu
  url: https://www.niklaas.eu
